image:
  file: .gitpod.Dockerfile

ports:
  # vnc port
  - port: 6080
    onOpen: open-browser
# other ports that are open for some reason
  - port: 1250
    onOpen: ignore
  - port: 1735
    onOpen: ignore
  - port: 5900
    onOpen: ignore

vscode:
  extensions:
    - https://github.com/microsoft/vscode-cpptools/releases/download/1.1.3/cpptools-linux.vsix
    - redhat.java@0.73.0
    - vscjava.vscode-java-dependency@0.16.0
    - vscjava.vscode-java-debug@0.30.0
    - wpilibsuite.vscode-wpilib@2021.2.2
